title: RENOMIZER's personal blog
tagline: A place where I do stuff

author:
  name: Konstantin
  email: pickledradish@tutanota.com

description: >- # this means to ignore newlines until "baseurl:"
  This is my personal webpage where
  I post updates on my projects
  and other stuff

baseurl: "" # the subpath of your site, e.g. /blog
domain: "renomizer.github.io"
url: "https://renomizer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter:
  username: ITS_NO_USE__
  card: summary

logo: /assets/favicon.png

social:
  name: Konstantin
  links:
    - https://twitter.com/ITS_NO_USE__
    - https://github.com/RENOMIZER

webmaster_verifications:
  google: klNuE8cm6_V-qUy0veaOTfrHmghRVSY1-fgbPZJ526Q

header_pages:
  - about.markdown

minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/RENOMIZER", title: GitHub }
    - { platform: twitter, user_url: "https://twitter.com/ITS_NO_USE__", title: Twitter  }
    - { platform: instagram, user_url: "https://instagram.com/Renomizer_MC", title: Instagram  }

show_excerpts: true

# Build settings
# theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
